// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC42VWDBzMQv4KG111tXOtT_onAQwsEfZI',
    appId: '1:445120481576:android:cf3a34a750712ba02fe81d',
    messagingSenderId: '445120481576',
    projectId: 'wakegaurd',
    storageBucket: 'wakegaurd.firebasestorage.app',
    androidClientId:
        '445120481576-2t5kcb9jd3chp075ccd2vg1v9952eruo.apps.googleusercontent.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwen6hSYJG6ueKDNJT7Hbi0F6VgVVKrDQ',
    appId: '1:445120481576:ios:56d10a7ea5f783c02fe81d',
    messagingSenderId: '445120481576',
    projectId: 'wakegaurd',
    storageBucket: 'wakegaurd.firebasestorage.app',
    iosClientId:
        '445120481576-afrmeccejlokq2g2f2dj261hu0bg7at2.apps.googleusercontent.com',
    iosBundleId: 'com.mekylealam.wakeguardalarm.a74sa4d686b',
  );
}
